### ISSUE TITLE
count statistic?

### ISSUE THREAD

**Issue by debboutr** [perrygeo/python-rasterstats#104]
I'm wondering about the count statistic...this should be a count of all the cells of the raster in the given feature correct?

**Comment by perrygeo** [comment]
@debboutr it's a count of the cells containing data - cells with nodata are not reflected.

**Comment by debboutr** [comment]
I'm getting some strange results in the count field for some reason the values are too low. You can download the files that I am working with below if you want to give it a try.  Below is an image of the highest count values that I am getting in the returned list of dictionaries after running the Catchment shapefile with the clay raster in the rasterstats function.  There is a .py script in the file folder on google Drive that you can use to run what I have.  The zonalstats_catchment.csv is a table that shows the values that we should be seeing. I would appreciate any help you could offer thanks!

![count_vals](https://cloud.githubusercontent.com/assets/7052993/11904192/44729766-a573-11e5-8a02-1a42569f0eeb.PNG)

[link to Files on Google Drive!](https://drive.google.com/folderview?id=0B_WKyKlsG-QjZXROTFpCMXVDS3M&usp=sharing)

**Comment by perrygeo** [comment]
I'm not sure what leads you to believe that `zonalstats_Catchment.csv` is correct. It's most certainly wrong, or at least it's not is the same order as the `Catchments.shp` you provided or run against a different raster or something.

In `zonalstats_Catchment.csv`:
```
FID,COUNT
0,1390.0
```
So the first feature covers 1390 pixels? 

The raster pixel size is 1000 m or 1 sq km. That would mean the area of the first polygon would be roughly 1390 sq km. But the attribute table itself says the area is 1.25 sq km. 

The csv is incorrect and the results of zonal stats is valid. Max pixels counts of ~450 is to be expected since the US catchments are roughly that many sq km.

**Comment by perrygeo** [comment]
@debboutr - just out of curiosity, where did you get that soil data? If you need the data internationally for the catchments in canada you could check out http://www.fao.org/soils-portal/soil-survey/soil-maps-and-databases/harmonized-world-soil-database-v12/en/
