### ISSUE TITLE
memoryerror exception on raster file in specific projection

### ISSUE THREAD

**Issue by demiurg** [perrygeo/python-rasterstats#107]
I have a very simple test case, a shapefile, and a raster file in a latlon grid projection. When running stats function it generates an exception:

```
python(36508,0x7fff7a4cc000) malloc: *** mach_vm_map(size=362320535494656) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "./create_stats.py", line 56, in <module>
    main()
  File "./create_stats.py", line 52, in main
    create_stats(r, p, date)
  File "./create_stats.py", line 22, in create_stats
    geojson = zonal_stats(shp_file, tif_file, stats='mean sum', geojson_out=True)
  File "/net/ellis/usr/local/home/pavel/code/ricedss/.venv/lib/python2.7/site-packages/rasterstats/main.py", line 21, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))
  File "/net/ellis/usr/local/home/pavel/code/ricedss/.venv/lib/python2.7/site-packages/rasterstats/main.py", line 136, in gen_zonal_stats
    fsrc = rast.read(bounds=geom_bounds)
  File "/net/ellis/usr/local/home/pavel/code/ricedss/.venv/lib/python2.7/site-packages/rasterstats/io.py", line 288, in read
    new_array = self.src.read(self.band, window=win, boundless=True, masked=masked)
  File "rasterio/_io.pyx", line 793, in rasterio._io.RasterReader.read (rasterio/_io.c:10053)
MemoryError
```

The test data are in
http://oka.ags.io/scratch/

failing code is
```
stats = zonal_stats("RRD.shp", "RRD_rice_2014157.tif", stats='mean sum', geojson_out=True)
```

working code on reprojected data works
```
stats = zonal_stats("RRD_sinu.shp", "RRD_rice_2014157_sinu.tif", stats='mean sum', geojson_out=True)
```

version is '0.10.0'

**Comment by perrygeo** [comment]
@demiurg Very strange. The data is small enough so I can't figure out why there might be a memory error. Looking into it...

**Comment by demiurg** [comment]
yeah, its downright tiny, and i have 140mb file in another projection processing in 2s. it's probably a seg fault of some kind

**Comment by demiurg** [comment]
Also, it happens on both linux and osx.

**Comment by perrygeo** [comment]
I can reproduce this. It's due to a projection mismatch: the raster is in latlon WGS84 projection while the shapefile is in Albers. `rasterstats` assumes that your data is in the same projection and will try to read the data in from the raster as specified on the cartesian coordinate system - which in this case means allocating a gigantic array of nodata.

To fix, I'd suggest projecting the `RRD.shp` file to the projection of the original raster.

In terms of catching these situations and warning about them, it's tricky: see https://github.com/perrygeo/python-rasterstats/issues/26#issuecomment-64965255

**Comment by demiurg** [comment]
wow, thanks so much for looking into this. I can understand the comment, but it seems like it's also a good idea to deal somehow with exceptions that can arise when these projection mismatches occur. perhaps a size of the zone in the reference raster projection can be sanity checking not to be more than a thousand times the area. or perhaps on exception spatial extents and/or projection info can be retrieved and displayed.

**Comment by perrygeo** [comment]
Comparing projections isn't currently viable because there's no reliable way to do it and it's not required that inputs have a projection defined. It'd be great to have a solution to this but it really doesn't exist and, if it did, would belong in a different library.

We can't compare spatial extents up front since many input methods allow for streaming iterators (the spatial extent of the full dataset isn't known until you've finished iterating through all the features). We do however known the raster extent up front...

I like the idea of comparing spatial extents at a geometry level - add some logic that says "don't even bother reading the raster if the geometry extent doesn't overlap with the raster extent". It won't fix every case but it should catch some of them.  I'll open a separate ticket to that effect.

**Comment by demiurg** [comment]
yeah, I think it would catch a few and help optimize, I'll definitely look at that ticket!
