### ISSUE TITLE
multicore?

### ISSUE THREAD

**Issue by foobarbecue** [perrygeo/python-rasterstats#120]
Is it possible to take advantage of multiple cores when calculating zonal statistics? If not, could this feature be added?

**Comment by perrygeo** [comment]
I played around with the idea of implementing multi-process parallelism internally but decided against it (for now) because it added significant complexity to the core functions.

Since each vector feature can be analyzed independent of other features, you can achieve parallelism by running several operations over subsets of your vector data and joining the lists.

I added an example of such usage here: https://github.com/perrygeo/python-rasterstats/blob/master/examples/multiproc.py

Let me know if you have any questions about it.

**Comment by foobarbecue** [comment]
Great! Thanks for the example -- I think that method will work for all of my applications.
