### ISSUE TITLE
Include selected polygon fields with output

### ISSUE THREAD

**Issue by owenscott** [perrygeo/python-rasterstats#137]
Just trying this module out for the first time - really awesome. Works well out of the box and clear documentation. Very excited that this exists!

Was wondering about the potential to include an optional argument to `zonal_stats` which specifies selected attribute fields from each polygon to include with the output. For instance, in my case I want to include a single ID attribute with each polygon in the output so that I can join the zonal stats back onto a Geopandas dataframe without having to trust that the dataframe and the zonal stats function have read in the polygons in the same order. I'm accomplishing this right now by passing `geojson=True` to the `zonal_stats` function and then plucking the stats fields along w/ the ID from `attributes`, but presumably that involves  some computational effort that's not getting used for anything. If i could instead pass `include_attributes=['my_id_field']` or something I'd find it a lot cleaner.

Apologies if this is already possible and I'm missing it. Had a look in the source and docs but certainly well short of an exhaustive search!

**Comment by perrygeo** [comment]
@owenscott Thanks for the suggestion but I'm not interested in including something like this in zonal stats. What you're talking about is an attribute filtering operation. This library is only concerned with vector-on-raster computations. There is great value in building simple pieces that can be composed together, rather than a few big pieces that do everything.

IOW this is 👍 
```
init_results = zonal_stats(vector, raster, geojson_out=True)
results = my_filter(init_results)
```

Because it can be composed with other geospatial operations that also produce geojson-like features:

```
init_results = buffer_features(vector, distance=10)
results = my_filter(init_results)
```

The alternative, mixing operations into a single function, leads to fragmented design and complexity:

```
zonal_stats(vector, raster, geojson_out=True, included_attributes=['id'])
# a slightly different implementation
buffer_features(vector, distance=10, select_attr='id')
```
