### ISSUE TITLE
Question: Can we set an analysis mask for rasterstats?

### ISSUE THREAD

**Issue by XiaopingDu** [perrygeo/python-rasterstats#143]
Hi Matthew,

I am doing a large scale data analysis using image tiles such as Hansen Global Forest Change Data. 
I do not want water areas to be calculated and I have a global water mask layer.
Can we set a mask for rasterstats just like mask environment setting in Arcgis?
http://pro.arcgis.com/en/pro-app/tool-reference/environment-settings/mask.htm

Thank you!
Xiaoping

**Comment by sgoodm** [comment]
I would suggest using rasterio to read in your data and mask layers, then use numpy to create a masked array and set the masked values to the nodata value. you can either output this as a new raster for use with rasterstats (suggest doing this) or pass it directly to rasterstats as an ndarray along with the affine info from one of the original rasters and the nodata value

should be pretty straight forward with hansen since they provide the datamask layer at the same resolution

you could also probably accomplish this with the `zone_func` argument
https://github.com/perrygeo/python-rasterstats/pull/132

**Comment by XiaopingDu** [comment]
Thank you @sgoodm !
Thank you for your suggestions. Yes, we should set nodata to original raster dataset if we can not set mask layer for rasterstats. However, there is a huge amount work to do for we have several global scale layers and there are lots of tiled images in each layer. So it would be a great convenience by setting mask for this tool.

**Comment by XiaopingDu** [comment]
Alternatively, I solved this problem by masking (clipping) my vector layer. I clipped the polygons in vector layer by polygons in mask layer. Thank you!
