### ISSUE TITLE
AttributeError when running zonal_stats

### ISSUE THREAD

**Issue by HenryW95** [perrygeo/python-rasterstats#173]
I'm trying to run zonal_stats and I'm getting the following error in the \__init__ function of io.py (line 242):
`AttributeError: 'GeneratorContextManager' object has no attribute 'transform'`

I've recreated the error with a variety of raster and vector data on a fresh virtual environment with rasterstats version 0.13.0.  I've experimented with using different combinations of rasterstats/rasterio versions but I'm still seeing the issue.  Any insight would be greatly appreciated.

Thanks!

**Comment by HenryW95** [comment]
Apologies, I was using reading the raster to memory before calling zonal_stats.  Simply supplying the file path to zonal_stats fixed the issue.

**Comment by Jwely** [comment]
I'd request this issue is re-opened.

An in-memory raster should be an accepted input. Being required to write it to disk and manage temporary files is a needlessly burdensome workaround.

**Comment by mhweber** [comment]
I would second request to re-open - I'm encountering the exact same issue with trying to use in-memory raster as opposed to passing the file path to zonal_stats.

**Comment by perrygeo** [comment]
In-memory rasters (more specifically a numpy array) can be passed as the raster data source but you need to also specify affine transform to tie it to geographic coordinates. See https://pythonhosted.org/rasterstats/manual.html#raster-data-sources

**Comment by janderson5417** [comment]
I see this issue is closed, but I've been stuck on specifying the affine instance most of the afternoon without any success. I've tried to baby-step my way through:

`tracts = fiona.open('data/tl_2021_06_tract.shp')`

`land_src = rasterio.open('data/land/NLCD_2019_Land_Cover_L48_20210604_rNuMWD3Z0SuUkIIVRc8K.tiff')
land_dict = land_src.profile`

`land_aff = land_dict['transform']
land_aff`
Affine(30.0, 0.0, -2158455.0,
       0.0, -30.0, 1591005.0)

`land_arr = land_src.read(1)
land_arr`
array([[52, 52, 52, ..., 52, 52, 52],
       [52, 52, 52, ..., 52, 52, 71],
       [52, 52, 52, ..., 52, 52, 71],
       ...,
       [ 0,  0,  0, ..., 31, 31, 31],
       [ 0,  0,  0, ..., 31, 31, 31],
       [ 0,  0,  0, ..., 31, 31, 31]], dtype=uint8)

`land_stats = zonal_stats(tracts, land_src, array = land_arr, affine = land_aff)`
...
AttributeError: '_GeneratorContextManager' object has no attribute 'transform'

What am I missing?

**Comment by janderson5417** [comment]
Thank you! I was traveling yesterday and couldn't try it out until today...if I can stretch your patience a bit, I tried the following based on your input:

`land_stats = zonal_stats(tracts, land_arr, affine = land_aff, nodata = -9999)`

It returned an empty list, although I can confirm data in QGIS for both the vector + raster data.

Maybe I implemented your response incorrectly?

**Comment by janderson5417** [comment]
@perrygeo --just for clarification, `affine = src.affine` yields the following error for me:

AttributeError: 'DatasetReader' object has no attribute 'affine'

**Comment by janderson5417** [comment]
@perrygeo --apologies, I've downloaded the repo files and am walking through your notes (which are fantastic)--thank you!!!
