### ISSUE TITLE
Rasterio MemoryFile Support?

### ISSUE THREAD

**Issue by Zeitsperre** [perrygeo/python-rasterstats#185]
I'm wondering if there is a supported way of accessing the rasterio `MemoryFile` format.

Unsurprisingly, I have been able to open and treat these files in a similar fashion to `NamedTemporaryFile`s by calling their `.name` but I get the impression from the docs these class objects have their own specific way of being handled (https://rasterio.readthedocs.io/en/stable/topics/memory-files.html). If these types of files aren't supported directly, I'm wondering if there is a hit to performance using the `.name` method.

**Comment by perrygeo** [comment]
Yes there is a performance hit due to the Rasterio implementation. Nothing that can be done about it downstream but it's a good topic for the Rasterio list :-)

In terms of raster support, paths and numpy arrays are fully supported: https://pythonhosted.org/rasterstats/manual.html#raster-data-sources
