### ISSUE TITLE
Rasterstats - Error - Rasterize Geom - Width and Height must be > 0

### ISSUE THREAD

**Issue by marcello-moreira** [perrygeo/python-rasterstats#218]
Hi Matthew,

I was trying to do the basic zonal statistics and I cannot get around this error.
I tried the process with different shapefiles (with polygons). The result was the same.
I am running it with Jupyter-Lab

Here is my env configuration with anaconda:
python                    3.7.7
rasterio                   1.1.4            py37h02db82b_0    conda-forge
rasterstats               0.14.0                     py_0
requests                  2.23.0             pyh8c360ce_2    conda-forge
rioxarray                 0.0.26                     py_0    conda-forge
xarray                     0.15.1

Here is my code:

shapefile=r'G:\gadm\version36 simplified\gadm36_2_simplified.shp'
temp_tif=r'E:\weather\data\gpm\late_source\temp.tif'
from rasterstats import zonal_stats
print(shapefile, temp_tif)
zonal_stats(shapefile,temp_tif)

Using those files:
[shapefile.zip](https://github.com/perrygeo/python-rasterstats/files/4722792/shapefile.zip)
[temp.zip](https://github.com/perrygeo/python-rasterstats/files/4722794/temp.zip)

Returning this error:
[error.txt](https://github.com/perrygeo/python-rasterstats/files/4722796/error.txt)

Objective:
I would like to use the gid_2 as the code to output the zonal statistics for each polygon 

Thanks in advance

**Comment by brendan-ward** [comment]
@marcello-moreira it looks like your raster is missing CRS information, which means that it can't be used as-is with the shapefile, which is using `EPSG:4326` (WGS 84 lat / long).

You need to first assign the correct CRS information to the raster. You will then need to transform the shapefile to that same CRS, so that they overlap in the same coordinate space.

**Comment by marcello-moreira** [comment]
Tks for the tip, Brendan. 
Indeed was missing.
I added the CRS.
Unfortunately the error remains the same.

Here is the tif with the EPSG:4326
[temp (2).zip](https://github.com/perrygeo/python-rasterstats/files/4726049/temp.2.zip)

**Comment by brendan-ward** [comment]
It looks like this is a case where the direction of the Y values is opposite of what rasterstats expects.  Typically, rasters are defined using a geotransform that starts at the upper left coordinate ("north up"), where each subsequent row of the raster is moving further south (negative Y).

In this case, it looks like the geotransform is at the bottom left.  This results in the window using to read each feature out of the raster being invalid.

While this is probably a bug in rasterstats, to get around your particular issue here, I think you need to recreate your raster with a north-up configuration.  This should just involve reading the raster using `rasterio`, updating the `transform` to be anchored from the upper left coordinate, with a negative y cell size, and writing that out to a new raster.

**Comment by perrygeo** [comment]
Thanks @brendan-ward. Yes this is a known issue in rasterstats: https://github.com/perrygeo/python-rasterstats/issues/98 

There has not been any progress building a general solution for the inverted y axis problem, yet.

**Comment by marcello-moreira** [comment]
Thanks guys, I recreated the raster north up and everything worked.

The full process chain is: Netcdf -> Xarray -> Geotiff -> Rasterstats

Then the code below discovers if the north is up/down, if lon is normal or inverted.
Then it will flip the data accordingly

import xarray
import numpy as np

xds=xarray.open_dataset(filename)

lat_start=xds.lat[0].item()
lat_end=xds.lat[xds.dims['lat']-1].item()
lon_start=xds.lon[0].item()
lon_end=xds.lon[xds.dims['lon']-1].item()
if lat_start<lat_end:
    lat_status='north down'
else:
    lat_status='north up'
if lon_start<lon_end:
    lon_status='lon normal'
else:
    lon_status='lon inverted'

da=xds.variable

# Flip the raster as necessary (based on the flasgs) 
if lat_status=='north down':
    da=np.flip(da.squeeze('time'),axis=0)
if lon_status=='inverted':
    da=np.flip(da.squeeze('time'),axis=1)

Hope it helps somebody in the same situation ...

Tks for you help

**Comment by dncardenasg** [comment]
Hello! 
I am new to Python, just learning.
I have the same problem and it persists after assigning the coordinate system.
I am working on a raster that I generated from the interpolation of some points, but the rasters are inverted (north down). When I try to do zonal statistics with Rasterstats this error is generated: "ValueError: negative dimensions are not allowed".

I don't know how to fix the transform.

This is the code I used for the interpolation (https://hatarilabs.com/ih-en/how-to-create-a-geospatial-raster-from-xy-data-with-python-pandas-and-rasterio- tutorial)

import numpy as np
import pandas as pd
from scipy.interpolate import griddata
import rasterio

chemData = pd.read_csv(r'path\201012.csv')

points = list(zip(chemData.longitude,chemData.latitude))
values = chemData.sm.values

#define raster resolution
rRes = 0.225

#create coord ranges over the desired raster extension
xRange = np.arange(chemData.longitude.min(),chemData.longitude.max()+rRes,rRes)
yRange = np.arange(chemData.latitude.min(),chemData.latitude.max()+rRes,rRes)

#create arrays of x,y over the raster extension
gridX,gridY = np.meshgrid(xRange, yRange)

gridPh = griddata(points, values, (gridX,gridY), method='cubic')

#definition of the raster transform array
from rasterio.transform import Affine
transform = Affine.translation(gridX[0][0]-rRes/2, gridY[0][0]-rRes/2)*Affine.scale(rRes,rRes)
print(transform)

#get crs as wkt
#from rasterio.crs import CRS
#rasterCrs=rasterio.crs.CRS.from_epsg(4326)

#definition, register and close of interpolated raster
interpRaster = rasterio.open('interpRaster_cubic.tif',
                                'w',
                                driver='GTiff',
                                height=gridPh.shape[0],
                                width=gridPh.shape[1],
                                count=1,
                                dtype=gridPh.dtype,
                                transform=transform,
                                )
interpRaster.write(gridPh,1)
interpRaster.close()

This is the resulting transform of the code:
| 0.23, 0.00, -79.87 |
| 0.00, 0.23, -3.94 |
| 0.00, 0.00, 1.00 |

I did not assign coordinate system because this error was generated:
"CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_identify: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db "

The origin points have these coordinates:
upper left: lat = 12.956, lon = -79.755
lower right: lat = -3.828, -66.009

I hope you can help me, thank you!

**Comment by perrygeo** [comment]
@dncardenasg I'm not sure but it appears to be an issue with your rasterio installation not being able to find the proj.db. I'd suggest checking out https://github.com/rasterio/rasterio#support  - the mailing list might be able to help.

**Comment by dncardenasg** [comment]
Thanks!
Do you know how I can generate the affine so that the negative dimensions error is not generated?

Thanks

**Comment by dncardenasg** [comment]
Thanks!

**Comment by mylesmc123** [comment]
@marcello-moreira You're saving deadlines two years later with that code snippet. Thank you!
