### ISSUE TITLE
CLI: Silent failure on malformed JSON in a sequence

### ISSUE THREAD

**Issue by indus** [perrygeo/python-rasterstats#251]
**Describe the bug**
When using a sequences of line-delimited Features as input the last Feature in the output is identical to the first, but the correct last Feature is missing.

**To Reproduce**
>1. How did you install rasterstats and its dependencies?
On Windows in a conda enviroment using the cli tool / rio plugin

2. What datasets are necessary to reproduce the bug? Please provide links to example data if necessary.
the [vectorfile input](https://gist.githubusercontent.com/indus/4c53db4b2fd244eba89aae10d63812bd/raw/7d782ee595438dc66981e57774412fb3b9d6f07b/h3_res0_seq_split.json)
any rasterfile (global coverage to fit the vectorfile); not so easy to provide due to licence
the [vectorfile output](https://gist.githubusercontent.com/indus/4c53db4b2fd244eba89aae10d63812bd/raw/7d782ee595438dc66981e57774412fb3b9d6f07b/h3_res0_seq_split_stats.json)
(when you compare the `id` and `_mean` property of the first and last feature you see they are the same; id `80f3fffffffffff` the last of the input is missing in the output)

3. What code is necessary to reproduce the bug? Provide the code directly below or provide links to it.
```ps
cat .\h3_res0_seq_split.json | rio zonalstats --stats mean -r .\any_global.nc --sequence | out-file -encoding utf8 ./test_rio6.json
```

**Comment by perrygeo** [comment]
@indus it looks like the [original vector input](https://gist.githubusercontent.com/indus/4c53db4b2fd244eba89aae10d63812bd/raw/7d782ee595438dc66981e57774412fb3b9d6f07b/h3_res0_seq_split.json) contains some rows with invalid JSON (line 122 is missing a closing `}`)

When I fix the json, I'm getting the correct results back.

Ideally, the rasterstats CLI should have thrown an exception and told you about the malformed JSON instead of silently failing in a strange way.

**Comment by indus** [comment]
oh - I should have seen this myself. Sorry for bothering you with broken input files; but thanks for looking into this.

**Comment by perrygeo** [comment]
This behavior is determined by the `cligj` plugin so there's not much we can do on the `rasterstats` side. 

https://github.com/mapbox/cligj/blob/c4500d88c0bebd9c31458ac9706e8dba3420ede1/cligj/features.py#L129-L133

If you'd like cligj to catch malformed json rather than silently failing, I'd suggest filing a bug report upstream. https://github.com/mapbox/cligj
