### ISSUE TITLE
clean up .travis.yml

### ISSUE THREAD

**Issue by perrygeo** [perrygeo/python-rasterstats#71]
right now it's just a big ball of hacks glued together to solve issues with versioning, build speed, etc. It's fragile and ugly and I don't want to maintain it anymore. 

Possibly switch to another CI solution that allows for faster build times via dependency containers?

**Comment by timcera** [comment]
I haven't converted all my projects over yet, but moved to using conda because of this exact issue and it works pretty well....

See
https://bitbucket.org/timcera/tstoolbox/src/22f5b40d04e239288e64fe32ed1f286faff8c598/.travis.yml?at=master
 for an example.  I found bits and pieces around the Internet so you might see similar code in other places.

**Comment by perrygeo** [comment]
Removing geopandas and scipy from the dev dependencies was a huge win for build times and reducing complexity of the travis config. See 02fc633269632b57424f619a4fbe205855c02657
